### ISSUE TITLE
Not working for V9

### ISSUE THREAD

**Issue by JackVanson** [concretecms/cloudflare_proxy#13]
When i try to install the package on my V9 site i get this error.

Too few arguments to function Symfony\Component\HttpFoundation\Request::setTrustedProxies(), 1 passed in /home/website
![error](https://user-images.githubusercontent.com/3705665/152816038-f8dff2ce-7310-4f69-94a1-16706183a31f.jpg)
/public_html/packages/cloudflare_proxy/src/CloudflareServiceProvider.php on line 31 and exactly 2 expected

**Comment by Samurai016** [comment]
Check pull request #15 to fix it.
